--------------------------------------------------------
--  Fichier créé - mardi-février-24-2026
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "TASNIM"."CLIENT"
   (	"ID" NUMBER,
        "NOM" VARCHAR2(50),
        "PRENOM" VARCHAR2(50),
        "TELEPHONE" VARCHAR2(20),
        "EMAIL" VARCHAR2(100),
        "ADRESSE" VARCHAR2(150),
        "DATE_INSCRIPTION" DATE,
        "TYPE_CLIENT" VARCHAR2(20),
        "TYPE_HUILE_PREFERE" VARCHAR2(20),
        "EMBALLAGE_PREFERE" VARCHAR2(10),
        "TOTAL_ACHAT" NUMBER(10,2),
        "POINTS_FIDELITE" NUMBER,
         PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
         CONSTRAINT "CHK_EMBALLAGE" CHECK (emballage_prefere IN ('1L','3L','5L')) ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
REM INSERTING into TASNIM.CLIENT
SET DEFINE OFF;
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('9','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('10','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('11','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('12','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('13','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('14','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('15','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('16','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('1','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('2','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('3','mkadmini','tasnim','53922357','manouba','manouba',to_date('20/02/26','DD/MM/RR'),'profisionnel','bio','5L','100','2');
Insert into TASNIM.CLIENT (ID,NOM,PRENOM,TELEPHONE,EMAIL,ADRESSE,DATE_INSCRIPTION,TYPE_CLIENT,TYPE_HUILE_PREFERE,EMBALLAGE_PREFERE,TOTAL_ACHAT,POINTS_FIDELITE) values ('4','mk','tas','42554545','bardo','bardo',to_date('15/03/26','DD/MM/RR'),'particulier','vierge','3L','60','6');
--------------------------------------------------------
--  DDL for Index SYS_C007386
--------------------------------------------------------

  CREATE UNIQUE INDEX "TASNIM"."SYS_C007386" ON "TASNIM"."CLIENT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TASNIM"."CLIENT_TRIGGER"
BEFORE INSERT ON TASNIM.CLIENT
FOR EACH ROW
BEGIN
    :NEW.ID := CLIENT_SEQ.NEXTVAL;
END;

ALTER TRIGGER "TASNIM"."CLIENT_TRIGGER" ENABLE
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TASNIM"."CLIENT" ADD CONSTRAINT "CHK_EMBALLAGE" CHECK (emballage_prefere IN ('1L','3L','5L')) ENABLE
  ALTER TABLE "TASNIM"."CLIENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
